"use client";

import { useState } from "react";

const demoWorkouts = [
  ["Monday · Lower Body", "Goblet squat", "3 × 10", "Controlled", "60 sec"],
  ["Wednesday · Upper Body", "Dumbbell row", "3 × 8 each", "2-1-2", "45 sec"],
  ["Friday · Full Body", "Romanian deadlift", "3 × 10", "Slow lowering", "75 sec"],
];

export function CustomerExperiencePreview() {
  const [view, setView] = useState("signup");
  return <section className="lift-preview">
    <div className="lift-preview__banner"><strong>Customer experience demonstration</strong><span>Sample information only—no real client data.</span></div>
    <nav className="lift-suite__tabs" aria-label="Customer demo sections">{["signup", "home", "book", "program", "progress", "pay"].map(item => <button key={item} className={view === item ? "is-active" : ""} onClick={() => setView(item)}>{item}</button>)}</nav>
    {view === "signup" && <section className="lift-lab-card"><p className="eyebrow">What a new customer sees</p><h2>Join Madie’s Lift Lab</h2><p className="lift-lab-card__intro">A short account form asks for the customer’s name, email, optional phone number, and password.</p><div className="lift-preview__signup-fields"><span>Full name</span><span>Email</span><span>Phone (optional)</span><span>Password</span></div><label className="lift-lab-disclaimer lift-preview__terms"><input type="checkbox" disabled /><span><strong>Terms and acknowledgment.</strong> The customer confirms that Madie’s Lift Lab is an independent paid personal-training service, separate from Southern Iron Fitness and not included with a Southern Iron Fitness membership. Optional progress photos require a separate opt-in and remain private.</span></label><button className="button" disabled>Create My Account (Demo)</button><p><small>The customer sees this as normal signup terms. Legal recordkeeping language and archive controls are never shown in the customer account.</small></p></section>}
    {view === "home" && <div className="lift-suite__metrics"><article><strong>3</strong><span>Sessions completed</span></article><article><strong>2 weeks</strong><span>Current streak</span></article><article><strong>Tue 5:30</strong><span>Next session</span></article><article><strong>Active</strong><span>Strength foundation</span></article></div>}
    {view === "book" && <div className="lift-lab-admin-grid"><section className="lift-lab-card"><p className="eyebrow">Step 1</p><h2>Choose a session</h2><label className="lift-preview__choice"><input type="radio" defaultChecked /> Private Training · 60 min</label><label className="lift-preview__choice"><input type="radio" /> Movement Check-In · 30 min</label></section><section className="lift-lab-card"><p className="eyebrow">Step 2</p><h2>Pick an opening</h2><div className="lift-preview__times"><button>Tue · 5:30 PM</button><button>Thu · 4:00 PM</button><button>Sat · 9:00 AM</button></div><p>Madie approves every request before it is booked.</p></section></div>}
    {view === "program" && <section className="lift-lab-card"><p className="eyebrow">Strength Foundation · 3 days weekly</p><h2>Your workout prescription</h2><p>Goal: build confidence, consistency, and foundational strength.</p><div className="lift-suite__list">{demoWorkouts.map(row => <article key={row[0]}><div><strong>{row[0]}</strong><span>{row[1]} · {row[2]} · Tempo {row[3]} · {row[4]} rest</span></div><button className="lift-preview__small">Log workout</button></article>)}</div></section>}
    {view === "progress" && <div className="lift-suite__stack"><div className="lift-suite__metrics"><article><strong>9</strong><span>Workouts logged</span></article><article><strong>+15 lb</strong><span>Best squat progress</span></article><article><strong>90%</strong><span>Attendance</span></article></div><section className="lift-lab-card"><h2>Optional progress photos</h2><p className="lift-lab-card__intro">Off by default. If the client opts in, only that client and Madie can view the private photos. Southern Iron Fitness and the master administrator cannot access them.</p><div className="lift-photo-slots"><article><span>DATE STARTED</span><strong>Private starting photo</strong><small>Sep 6, 2026</small></article><article><span>SIX MONTHS</span><strong>Progress comparison</strong><small>Due Mar 6, 2027</small></article><article><span>CHECK-INS</span><strong>Optional visit photos</strong><small>Add only when wanted</small></article></div></section></div>}
    {view === "pay" && <section className="lift-lab-card"><p className="eyebrow">Paid directly to Madie’s Lift Lab</p><h2>Complete your deposit</h2><ol className="lift-preview__steps"><li>Open Madie’s verified Venmo link.</li><li>Pay the amount Madie assigned to this session.</li><li>Enter the confirmation or privately attach a screenshot.</li><li>Madie verifies it in her dashboard.</li></ol><button className="button">Open Venmo (Demo)</button><p><small>This preview never opens a payment app or submits information.</small></p></section>}
  </section>;
}

export function TrainerExperiencePreview() {
  const [view, setView] = useState("today");
  return <section className="lift-preview">
    <div className="lift-preview__banner"><strong>Madie’s dashboard demonstration</strong><span>Sample information only—no real client data or financial records.</span></div>
    <nav className="lift-suite__tabs" aria-label="Trainer demo sections">{["today", "calendar", "clients", "builder", "progress", "payments"].map(item => <button key={item} className={view === item ? "is-active" : ""} onClick={() => setView(item)}>{item}</button>)}</nav>
    {view === "today" && <div className="lift-suite__metrics"><article><strong>2</strong><span>Requests to approve</span></article><article><strong>4</strong><span>Today’s sessions</span></article><article><strong>8</strong><span>Active programs</span></article><article><strong>1</strong><span>Payment to review</span></article></div>}
    {view === "calendar" && <section className="lift-lab-card"><h2>Publish availability</h2><p>Madie opens individual times, repeats a weekly time, or publishes beyond the normal 14-day window whenever she wants.</p><div className="lift-preview__week">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <article key={day}><strong>{day}</strong><span>{index % 2 ? "4:00 · 5:30" : "9:00 · 10:30"}</span></article>)}</div></section>}
    {view === "clients" && <section className="lift-lab-card"><h2>Clients</h2><div className="lift-suite__list"><article><div><strong>Jordan M. · MLL-DEMO</strong><span>Approved · Strength Foundation</span></div><button className="lift-preview__small">Freeze</button></article><article><div><strong>Taylor R. · MLL-DEMO</strong><span>Waiting for approval</span></div><div className="lift-lab-request-actions"><button>Approve</button><button>Decline</button></div></article></div></section>}
    {view === "builder" && <section className="lift-lab-card"><p className="eyebrow">Program builder</p><h2>Strength Foundation</h2><div className="lift-preview__builder"><label>Goal<input readOnly value="Build foundational strength" /></label><label>Weekly frequency<input readOnly value="3 sessions" /></label><label>Training day<input readOnly value="Monday · Lower Body" /></label><label>Exercise<input readOnly value="Goblet squat" /></label><label>Prescription<input readOnly value="3 × 10 · 60 sec · controlled" /></label><label>Madie’s instruction<textarea readOnly value="Brace first. Stop with two good reps left." /></label></div><button className="button">Save to Client (Demo)</button></section>}
    {view === "progress" && <section className="lift-lab-card"><h2>Private client progress</h2><p>Madie sees workout history, attendance, check-ins, and—only after client opt-in—the private photo timeline. Every photo view is logged.</p><div className="lift-photo-slots"><article><span>CONSENT</span><strong>Client opted in</strong><small>May withdraw anytime</small></article><article><span>STARTED</span><strong>Sep 6, 2026</strong><small>Private comparison</small></article><article><span>SIX MONTHS</span><strong>Mar 6, 2027</strong><small>Reminder scheduled</small></article></div></section>}
    {view === "payments" && <section className="lift-lab-card"><h2>Madie’s private payment workflow</h2><ol className="lift-preview__steps"><li>Madie sets each service price and optional deposit.</li><li>The client pays Madie directly by Venmo or in person.</li><li>Madie reviews the reference or private proof.</li><li>Only Madie and the client see amounts and records.</li></ol><p className="lift-preview__privacy"><strong>Southern Iron Fitness does not see what Madie charges or earns.</strong></p></section>}
  </section>;
}
