"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type DemoState = {
  account: "not_started" | "pending" | "approved";
  appointment: "none" | "pending" | "confirmed";
  program: "none" | "active" | "frozen";
  workouts: number;
  photoOptIn: boolean;
  startPhoto: boolean;
  sixMonthPhoto: boolean;
  payment: "not_requested" | "awaiting" | "submitted" | "verified";
  appointmentSlotId: string | null;
  slots: DemoSlot[];
};

type DemoSlot = { id: string; day: string; start: string; end: string; status: "open" | "blocked" };
const starterSlots: DemoSlot[] = [
  { id: "demo-tue-1730", day: "Tue", start: "17:30", end: "18:30", status: "open" },
  { id: "demo-thu-1600", day: "Thu", start: "16:00", end: "17:00", status: "open" },
];
const initialState: DemoState = { account: "not_started", appointment: "none", program: "none", workouts: 0, photoOptIn: false, startPhoto: false, sixMonthPhoto: false, payment: "not_requested", appointmentSlotId: null, slots: starterSlots };
const demoKey = "lift-lab-master-experience-test-v1";

function useDemoState() {
  const [demo, setDemo] = useState<DemoState>(initialState);
  const ready = useRef(false);
  useEffect(() => { queueMicrotask(() => { try { const saved = sessionStorage.getItem(demoKey); if (saved) setDemo({ ...initialState, ...(JSON.parse(saved) as Partial<DemoState>) }); } catch { /* start clean */ } ready.current = true; }); }, []);
  useEffect(() => { if (!ready.current) return; try { sessionStorage.setItem(demoKey, JSON.stringify(demo)); } catch { /* nonessential */ } }, [demo]);
  return [demo, setDemo] as const;
}

function Status({ children }: { children: string }) {
  return <span className={`lift-lab-status lift-lab-status--${children}`}>{children.replaceAll("_", " ")}</span>;
}

const slotLabel = (slot?: DemoSlot) => slot ? `${slot.day} · ${new Date(`2000-01-01T${slot.start}`).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}` : "Time not selected";

export function CustomerExperiencePreview() {
  const [demo, setDemo] = useDemoState();
  const [view, setView] = useState("signup");
  const [notice, setNotice] = useState("");
  const update = (change: Partial<DemoState>, message: string) => { setDemo(current => ({ ...current, ...change })); setNotice(message); };
  const reset = () => { setDemo(initialState); setView("signup"); setNotice("The customer test was reset."); };
  const submitSignup = (event: FormEvent) => { event.preventDefault(); update({ account: "pending" }, "Sample signup sent. Switch to Madie’s View to approve it."); setView("home"); };
  const selectedSlot = demo.slots.find(slot => slot.id === demo.appointmentSlotId);

  return <section className="lift-preview">
    <div className="lift-preview__banner"><div><strong>Live customer experience test</strong><span>Safe sample account · MLL-DEMO-001 · no real customer data</span></div><button className="lift-preview__small" onClick={reset}>Reset test</button></div>
    <nav className="lift-suite__tabs" aria-label="Customer test sections">{["signup", "home", "book", "schedule", "program", "progress", "pay"].map(item => <button key={item} className={view === item ? "is-active" : ""} onClick={() => setView(item)}>{item}</button>)}</nav>
    {notice ? <p className="lift-lab-message" role="status">{notice}</p> : null}

    {view === "signup" && <section className="lift-lab-card"><p className="eyebrow">Exactly what a new customer experiences</p><h2>Join Madie’s Lift Lab</h2><form className="lift-lab-form" onSubmit={submitSignup}><label>Full name<input defaultValue="Jordan Demo" required /></label><label>Email<input type="email" defaultValue="customer-preview@example.com" required /></label><label>Phone <span>(optional)</span><input type="tel" placeholder="Optional" /></label><label>Password<input type="password" defaultValue="Preview123!" required /></label><label className="lift-lab-disclaimer"><input type="checkbox" required /><span><strong>Terms and acknowledgment.</strong> I understand that Madie’s Lift Lab is an independent paid personal-training service, separate from Southern Iron Fitness and not included with a Southern Iron Fitness membership. Optional progress photos require a separate opt-in and remain private.</span></label><button className="button">Create Sample Account</button></form><p><small>This test stores only temporary sample state in this browser. Nothing is added to the customer database.</small></p></section>}

    {view === "home" && <div className="lift-suite__stack"><div className="lift-suite__metrics"><article><strong>{demo.workouts}</strong><span>Workouts completed</span></article><article><strong>{demo.appointment === "confirmed" ? "Tue 5:30" : "—"}</strong><span>Next session</span></article><article><strong>{demo.program}</strong><span>Program status</span></article><article><strong>{demo.account}</strong><span>Account status</span></article></div>{demo.account !== "approved" ? <section className="lift-lab-card"><h2>{demo.account === "pending" ? "Madie has your signup." : "Create the sample account first."}</h2><p>{demo.account === "pending" ? "This is the holding screen a real customer sees until Madie approves the request." : "Open Signup to begin the customer journey."}</p><button className="button" onClick={() => setView("signup")}>Go to Signup</button></section> : <section className="lift-lab-card"><h2>Welcome, Jordan.</h2><p>Your account is approved. Request a session, follow your program, track progress, and handle deposits from these tabs.</p><button className="button" onClick={() => setView("book")}>Find a Time</button></section>}</div>}

    {view === "book" && <section className="lift-lab-card"><p className="eyebrow">Private sessions</p><h2>Request an appointment</h2>{demo.account !== "approved" ? <><p>Madie must approve this sample account first.</p><button className="button" onClick={() => setView("home")}>View Account Status</button></> : demo.slots.some(slot => slot.status === "open") ? <form className="lift-lab-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); update({ appointment: "pending", appointmentSlotId: String(form.get("slotId")) }, "Appointment requested. Switch to Madie’s View to approve it."); setView("schedule"); }}><label>Service<select defaultValue="private"><option value="private">Private Training · 60 minutes</option><option value="checkin">Movement Check-In · 30 minutes</option></select></label><label>Available time<select name="slotId" defaultValue="" required><option value="" disabled>Choose a test time</option>{demo.slots.filter(slot => slot.status === "open").map(slot => <option key={slot.id} value={slot.id}>{slotLabel(slot)}</option>)}</select></label><label>Anything Madie should know? <span>(optional)</span><textarea placeholder="Optional note" /></label><button className="button">Request This Time</button></form> : <p>Madie has no open sample times. Open Madie Preview → Calendar to add or reopen one.</p>}</section>}

    {view === "schedule" && <section className="lift-lab-card"><h2>Your schedule</h2>{demo.appointment === "none" ? <><p>No appointment requested yet.</p><button className="button" onClick={() => setView("book")}>Request an Appointment</button></> : <div className="lift-suite__list"><article><div><strong>Private Training</strong><span>{slotLabel(selectedSlot)}</span></div><Status>{demo.appointment}</Status></article></div>}</section>}

    {view === "program" && <section className="lift-lab-card"><p className="eyebrow">{demo.program} program</p><h2>{demo.program === "none" ? "Your program will appear here." : "Strength Foundation"}</h2>{demo.program === "none" ? <p>Switch to Madie’s View to assign the sample program.</p> : <><p><strong>Goal:</strong> Build confidence, consistency, and foundational strength · 3 days weekly.</p>{demo.program === "frozen" ? <p className="lift-lab-message">This program is frozen. History is preserved and new workout logging is paused.</p> : null}<div className="lift-suite__list"><article><div><strong>Monday · Goblet squat</strong><span>3 × 10 · controlled tempo · 60 seconds rest</span></div>{demo.program === "active" ? <button className="lift-preview__small" onClick={() => update({ workouts: demo.workouts + 1 }, "Workout logged and progress card updated.")}>Log Workout</button> : <Status>frozen</Status>}</article></div></>}</section>}

    {view === "progress" && <div className="lift-suite__stack"><div className="lift-suite__metrics"><article><strong>{demo.workouts}</strong><span>Workouts logged</span></article><article><strong>{demo.workouts ? `${demo.workouts} week${demo.workouts === 1 ? "" : "s"}` : "—"}</strong><span>Consistency streak</span></article><article><strong>{demo.startPhoto ? "Saved" : "Optional"}</strong><span>Date-started photo</span></article></div><section className="lift-lab-card"><h2>Private progress photos</h2><p>Off by default. If the customer opts in, only that customer and Madie can access the photos. The master administrator cannot view them.</p>{!demo.photoOptIn ? <button className="button" onClick={() => update({ photoOptIn: true }, "Sample customer opted into private progress photos.")}>Opt In to Private Photos</button> : <><div className="lift-photo-consent lift-photo-consent--active"><strong>Private photo tracking is on.</strong><button className="lift-lab-text-button" onClick={() => update({ photoOptIn: false }, "Future photo tracking turned off. Training access is unchanged.")}>Turn Off</button></div><div className="lift-photo-slots"><article><span>Date Started</span><strong>{demo.startPhoto ? "Saved privately" : "Not added"}</strong><button className="lift-preview__small" onClick={() => update({ startPhoto: !demo.startPhoto }, demo.startPhoto ? "Sample starting photo removed." : "Sample starting photo saved privately.")}>{demo.startPhoto ? "Remove Sample" : "Add Sample"}</button></article><article><span>Six Months</span><strong>{demo.sixMonthPhoto ? "Saved privately" : "Due Mar 6, 2027"}</strong><button className="lift-preview__small" onClick={() => update({ sixMonthPhoto: !demo.sixMonthPhoto }, demo.sixMonthPhoto ? "Sample six-month photo removed." : "Sample six-month photo saved privately.")}>{demo.sixMonthPhoto ? "Remove Sample" : "Add Sample"}</button></article></div></>}</section></div>}

    {view === "pay" && <section className="lift-lab-card"><p className="eyebrow">Paid directly to Madie’s Lift Lab</p><h2>Payments</h2>{demo.payment === "not_requested" ? <p>Madie has not assigned a sample deposit yet. Switch to Madie’s View and create it.</p> : <><div className="lift-suite__list"><article><div><strong>Private Training · Sample deposit</strong><span>Venmo payment goes directly to Madie</span></div><Status>{demo.payment}</Status></article></div>{demo.payment === "awaiting" ? <div className="lift-master-actions"><a className="button" href="https://venmo.com/u/Madison-Rabalais-1" target="_blank" rel="noreferrer">Open Madie’s Venmo</a><button className="button button--outline" onClick={() => update({ payment: "submitted" }, "Sample confirmation sent to Madie for review.")}>Simulate Confirmation</button></div> : null}{demo.payment === "submitted" ? <p>Madie is reviewing the sample confirmation.</p> : null}</>}</section>}
  </section>;
}

export function TrainerExperiencePreview() {
  const [demo, setDemo] = useDemoState();
  const [view, setView] = useState("today");
  const [notice, setNotice] = useState("");
  const update = (change: Partial<DemoState>, message: string) => { setDemo(current => ({ ...current, ...change })); setNotice(message); };
  const selectedSlot = demo.slots.find(slot => slot.id === demo.appointmentSlotId);
  const updateSlot = (id: string, change: Partial<DemoSlot>) => { setDemo(current => ({ ...current, slots: current.slots.map(slot => slot.id === id ? { ...slot, ...change } : slot) })); setNotice("Sample time updated. Customer View now reflects the change."); };
  const addSlot = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const slot: DemoSlot = { id: crypto.randomUUID(), day: String(form.get("day")), start: String(form.get("start")), end: String(form.get("end")), status: "open" }; setDemo(current => ({ ...current, slots: [...current.slots, slot] })); setNotice(`${slotLabel(slot)} added to the sample calendar.`); event.currentTarget.reset(); };
  const removeSlot = (id: string) => { setDemo(current => ({ ...current, slots: current.slots.filter(slot => slot.id !== id), ...(current.appointmentSlotId === id ? { appointment: "none", appointmentSlotId: null } : {}) })); setNotice("Sample time removed. Any linked sample appointment was cleared."); };

  return <section className="lift-preview">
    <div className="lift-preview__banner"><div><strong>Live Madie experience test</strong><span>The same sample customer and workflow used in Customer View</span></div><Status>{demo.account}</Status></div>
    <nav className="lift-suite__tabs" aria-label="Trainer test sections">{["today", "calendar", "clients", "builder", "progress", "payments"].map(item => <button key={item} className={view === item ? "is-active" : ""} onClick={() => setView(item)}>{item}</button>)}</nav>
    {notice ? <p className="lift-lab-message" role="status">{notice}</p> : null}

    {view === "today" && <div className="lift-suite__stack"><div className="lift-suite__metrics"><article><strong>{demo.account === "pending" ? 1 : 0}</strong><span>Account requests</span></article><article><strong>{demo.appointment === "pending" ? 1 : 0}</strong><span>Appointment requests</span></article><article><strong>{demo.program === "active" ? 1 : 0}</strong><span>Active programs</span></article><article><strong>{demo.payment === "submitted" ? 1 : 0}</strong><span>Payments to review</span></article></div>{demo.account === "not_started" ? <section className="lift-lab-card"><h2>Test the approval workflow</h2><p>Create a safe pending sample customer here, then approve it exactly as Madie would.</p><button className="button" onClick={() => { update({ account: "pending" }, "Pending test customer created. Approve or decline it from Clients."); setView("clients"); }}>Create Pending Test Customer</button></section> : null}</div>}

    {view === "calendar" && <div className="lift-suite__stack"><section className="lift-lab-card"><p className="eyebrow">Editable sample calendar</p><h2>Monday–Sunday availability</h2><p>Every change below immediately appears in Customer View → Book. Nothing here touches Madie’s real schedule.</p><form className="lift-preview__slot-form" onSubmit={addSlot}><label>Day<select name="day" required defaultValue="Mon">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <option key={day}>{day}</option>)}</select></label><label>Start<input name="start" type="time" required /></label><label>End<input name="end" type="time" required /></label><button className="button">Add Test Time</button></form><div className="lift-preview__week">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <article key={day}><strong>{day}</strong>{demo.slots.filter(slot => slot.day === day).length ? demo.slots.filter(slot => slot.day === day).map(slot => <span key={slot.id}>{slotLabel(slot).replace(`${day} · `, "")} · {slot.status}</span>) : <span>No times</span>}</article>)}</div><div className="lift-suite__list">{demo.slots.length ? demo.slots.map(slot => <article key={slot.id}><div className="lift-preview__slot-fields"><label>Day<select value={slot.day} onChange={event => updateSlot(slot.id, { day: event.target.value })}>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <option key={day}>{day}</option>)}</select></label><label>Start<input type="time" value={slot.start} onChange={event => updateSlot(slot.id, { start: event.target.value })} /></label><label>End<input type="time" value={slot.end} onChange={event => updateSlot(slot.id, { end: event.target.value })} /></label></div><Status>{slot.status}</Status><div className="lift-lab-request-actions"><button onClick={() => updateSlot(slot.id, { status: slot.status === "open" ? "blocked" : "open" })}>{slot.status === "open" ? "Block" : "Reopen"}</button><button onClick={() => removeSlot(slot.id)}>Delete</button></div></article>) : <p>No sample times. Add one above.</p>}</div><button className="lift-preview__small" onClick={() => update({ slots: starterSlots }, "Example times restored. You can edit every time.")}>Restore Example Times</button></section>{demo.appointment !== "none" ? <section className="lift-lab-card"><h2>Appointment request</h2><div className="lift-suite__list"><article><div><strong>Jordan Demo · MLL-DEMO-001</strong><span>Private Training · {slotLabel(selectedSlot)}</span></div><Status>{demo.appointment}</Status>{demo.appointment === "pending" ? <div className="lift-lab-request-actions"><button onClick={() => update({ appointment: "confirmed" }, "Appointment approved. Customer Schedule now shows confirmed.")}>Approve</button><button onClick={() => update({ appointment: "none", appointmentSlotId: null }, "Appointment declined and the time reopened.")}>Decline</button></div> : null}</article></div></section> : null}</div>}

    {view === "clients" && <section className="lift-lab-card"><h2>Customer approvals</h2>{demo.account === "not_started" ? <div className="lift-lab-empty"><p>No pending test customer yet.</p><button className="button" onClick={() => update({ account: "pending" }, "Jordan Demo is now waiting for Madie’s approval.")}>Create Pending Test Customer</button></div> : <div className="lift-suite__list"><article><div><strong>Jordan Demo · MLL-DEMO-001</strong><span>Sample record—no real contact, payment, or photo data</span></div><Status>{demo.account}</Status>{demo.account === "pending" ? <div className="lift-lab-request-actions"><button onClick={() => update({ account: "approved" }, "Sample customer approved. Customer View is now unlocked.")}>Approve</button><button onClick={() => update({ account: "not_started" }, "Sample customer request declined.")}>Decline</button></div> : null}{demo.program !== "none" ? <button className="lift-preview__small" onClick={() => update({ program: demo.program === "frozen" ? "active" : "frozen" }, demo.program === "frozen" ? "Program unfrozen." : "Program frozen with history preserved.")}>{demo.program === "frozen" ? "Unfreeze" : "Freeze"}</button> : null}</article></div>}</section>}

    {view === "builder" && <section className="lift-lab-card"><p className="eyebrow">Workout prescription builder</p><h2>Strength Foundation</h2><form className="lift-lab-form" onSubmit={event => { event.preventDefault(); update({ program: "active" }, "Program assigned. Open Customer View → Program to experience it."); }}><label>Customer<select defaultValue="jordan"><option value="jordan">Jordan Demo · MLL-DEMO-001</option></select></label><label>Goal<input defaultValue="Build foundational strength" /></label><label>Weekly frequency<input type="number" min="1" max="14" defaultValue="3" /></label><label>Training day<input defaultValue="Monday · Lower Body" /></label><label>Exercise<input defaultValue="Goblet squat" /></label><div className="lift-lab-form-row"><label>Sets<input type="number" defaultValue="3" /></label><label>Reps<input defaultValue="10" /></label></div><div className="lift-lab-form-row"><label>Rest<input defaultValue="60 seconds" /></label><label>Tempo<input defaultValue="Controlled" /></label></div><label>Madie’s instructions<textarea defaultValue="Brace first. Stop with two good reps left." /></label><button className="button">Assign Sample Program</button></form></section>}

    {view === "progress" && <section className="lift-lab-card"><h2>Customer progress</h2><div className="lift-suite__metrics"><article><strong>{demo.workouts}</strong><span>Workouts completed</span></article><article><strong>{demo.photoOptIn ? "Opted in" : "Off"}</strong><span>Private photos</span></article><article><strong>{demo.startPhoto ? "Saved" : "—"}</strong><span>Date started</span></article><article><strong>{demo.sixMonthPhoto ? "Saved" : "—"}</strong><span>Six months</span></article></div><p className="lift-preview__privacy"><strong>In the real system, only Madie and the individual customer can open progress photos. Your master account cannot view them.</strong></p></section>}

    {view === "payments" && <section className="lift-lab-card"><h2>Madie’s private payment workflow</h2><p>Real prices and earnings remain visible only to Madie and the customer. This sample uses no amount.</p>{demo.payment === "not_requested" ? <button className="button" onClick={() => update({ payment: "awaiting" }, "Sample deposit requested. Open Customer View → Pay.")}>Request Sample Deposit</button> : <div className="lift-suite__list"><article><div><strong>Jordan Demo · Private Training</strong><span>Direct Venmo or in-person payment</span></div><Status>{demo.payment}</Status>{demo.payment === "submitted" ? <div className="lift-lab-request-actions"><button onClick={() => update({ payment: "verified" }, "Sample payment verified. Customer View now shows verified.")}>Verify</button><button onClick={() => update({ payment: "awaiting" }, "Sample payment returned for correction.")}>Reject</button></div> : null}</article></div>}</section>}
  </section>;
}
